version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Python3/Dockerfile
    volumes:
    - type: bind
      source: "./slackbot_aws"
      target: "/root/dev/"
    tty: true
    env_file: .envrc
